server:
  port: 8082

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true
    username: appointment-service_user
    password: Password@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
